### ISSUE TITLE
Scap Rikishis Pictures

### ISSUE THREAD

**Issue by Christ-OFF** [Christ-OFF/sumolambdas#2]
Purpose : Removes ALL pictures from the app itself and let app loads them from AWS  
Create new DynamoDB  table
Extract image during scraping process and store (may require compression see warning)
Key is rikishi id

Provide Lambda to get image by rikishi id

Warning : DynamoDB limits individual records to 64 KB, Alternative use S3 !

**Comment by Christ-OFF** [comment]
update binary limit is 400kb : http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-data-types

**Comment by Christ-OFF** [comment]
Applications that work with Binary attributes must encode the data in Base64 format before sending it to DynamoDB. Upon receipt of the data, DynamoDB decodes it into an unsigned byte array and uses that as the length of the attribute.

**Comment by Christ-OFF** [comment]
Handle :
`2017-09-07 00:14:18 <> INFO  LambdaMethodHandler:Save failures 3
2017-09-07 00:14:18 <> ERROR LambdaMethodHandler:Error saving riskishis
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: One or more parameter values were invalid: An AttributeValue may not contain a null or empty binary type. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 82f617a5-a513-4bb6-a4c0-b68dfedfc187)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2186)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2162)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeBatchWriteItem(AmazonDynamoDBClient.java:575)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.batchWriteItem(AmazonDynamoDBClient.java:551)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.doBatchWriteItemWithRetry(DynamoDBMapper.java:1224)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.writeOneBatch(DynamoDBMapper.java:1166)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.batchWrite(DynamoDBMapper.java:1137)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.batchSave(AbstractDynamoDBMapper.java:173)
	at com.christoff.apps.sumolambda.LambdaMethodHandler.handleRikishis(LambdaMethodHandler.java:94)
	at com.christoff.apps.sumolambda.LambdaMethodHandler.handleRequest(LambdaMethodHandler.java:61)
	at com.christoff.apps.sumolambda.LambdaMethodHandler.main(LambdaMethodHandler.java:39)`

**Comment by Christ-OFF** [comment]
Pictures must be scrapped in its own lambda as a lambda cannot take more than 5mn

**Comment by Christ-OFF** [comment]
Check how a trigger from extract_info can work (may be add instead of replace/update)
